package com.mapper;

import com.entity.Buyticket;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuyticketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyticket
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("userId") Long userId, @Param("scenicId") Long scenicId, @Param("createTime") Date createTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyticket
     *
     * @mbggenerated
     */
    int insert(Buyticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyticket
     *
     * @mbggenerated
     */
    Buyticket selectByPrimaryKey(@Param("userId") Long userId, @Param("scenicId") Long scenicId, @Param("createTime") Date createTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyticket
     *
     * @mbggenerated
     */
    List<Buyticket> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyticket
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Buyticket record);

    /**
     * 获取某用户关于某景点的购票记录
     * @param userId
     * @param scenicId
     * @return
     */
	List<Buyticket> selectByUserSce(@Param("userId")Long userId, @Param("scenicId")Long scenicId);
}