package com.mapper;

import com.entity.Collect;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollectMapper extends BaseMapper<Collect> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("userId") Long userId, @Param("scenicId") Long scenicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated
     */
    int insert(Collect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated
     */
    Collect selectByPrimaryKey(@Param("userId") Long userId, @Param("scenicId") Long scenicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated
     */
    List<Collect> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Collect record);
    
    void del(@Param("userId")Long userId, @Param("scenicId")Long scenicId);
    
    /**
     * 根据userId查找所有收藏景点
     * @param userId
     * @return
     */
    List<Collect> selectByUserId(Long userId);
    
}