package com.entity;

import java.util.Date;

public class Buyticket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyticket.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyticket.scenic_id
     *
     * @mbggenerated
     */
    private Long scenicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyticket.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyticket.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyticket.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyticket.user_id
     *
     * @return the value of buyticket.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyticket.user_id
     *
     * @param userId the value for buyticket.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyticket.scenic_id
     *
     * @return the value of buyticket.scenic_id
     *
     * @mbggenerated
     */
    public Long getScenicId() {
        return scenicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyticket.scenic_id
     *
     * @param scenicId the value for buyticket.scenic_id
     *
     * @mbggenerated
     */
    public void setScenicId(Long scenicId) {
        this.scenicId = scenicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyticket.create_time
     *
     * @return the value of buyticket.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyticket.create_time
     *
     * @param createTime the value for buyticket.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyticket.count
     *
     * @return the value of buyticket.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyticket.count
     *
     * @param count the value for buyticket.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyticket.update_time
     *
     * @return the value of buyticket.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyticket.update_time
     *
     * @param updateTime the value for buyticket.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}