package com.entity;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_id
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_password
     *
     * @mbggenerated
     */
    private String rolePassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_identity
     *
     * @mbggenerated
     */
    private String roleIdentity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_id
     *
     * @return the value of role.role_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_id
     *
     * @param roleId the value for role.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_password
     *
     * @return the value of role.role_password
     *
     * @mbggenerated
     */
    public String getRolePassword() {
        return rolePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_password
     *
     * @param rolePassword the value for role.role_password
     *
     * @mbggenerated
     */
    public void setRolePassword(String rolePassword) {
        this.rolePassword = rolePassword == null ? null : rolePassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_identity
     *
     * @return the value of role.role_identity
     *
     * @mbggenerated
     */
    public String getRoleIdentity() {
        return roleIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_identity
     *
     * @param roleIdentity the value for role.role_identity
     *
     * @mbggenerated
     */
    public void setRoleIdentity(String roleIdentity) {
        this.roleIdentity = roleIdentity == null ? null : roleIdentity.trim();
    }
}