package com.entity;

import java.io.Serializable;
import java.util.List;

public class Scenic extends BaseEntity implements Serializable {
	
	private static final long serialVersionUID = -2484952994770561997L;
	private Integer ticketRemainder;
	private Province province;
    private City city;
    private List<Comment> commentList; 		   //景点的所有评论
    private List<Comment> commentListByUser;   //景点对应于某用户的评论
    private List<Buyticket> ticketListByUser;     //景点对应于某用户的购票
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.scenic_id
     *
     * @mbggenerated
     */
    private Long scenicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.scenic_name
     *
     * @mbggenerated
     */
    private String scenicName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.scenic_pos
     *
     * @mbggenerated
     */
    private String scenicPos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.scenic_score
     *
     * @mbggenerated
     */
    private Integer scenicScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.scenic_ticket_price
     *
     * @mbggenerated
     */
    private Integer scenicTicketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.scenic_type
     *
     * @mbggenerated
     */
    private String scenicType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.province_id
     *
     * @mbggenerated
     */
    private Long provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.city_id
     *
     * @mbggenerated
     */
    private Long cityId;
    
    private String scenicImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenic.del
     *
     * @mbggenerated
     */
    private Integer del;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.scenic_id
     *
     * @return the value of scenic.scenic_id
     *
     * @mbggenerated
     */
    public Long getScenicId() {
        return scenicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.scenic_id
     *
     * @param scenicId the value for scenic.scenic_id
     *
     * @mbggenerated
     */
    public void setScenicId(Long scenicId) {
        this.scenicId = scenicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.scenic_name
     *
     * @return the value of scenic.scenic_name
     *
     * @mbggenerated
     */
    public String getScenicName() {
        return scenicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.scenic_name
     *
     * @param scenicName the value for scenic.scenic_name
     *
     * @mbggenerated
     */
    public void setScenicName(String scenicName) {
        this.scenicName = scenicName == null ? null : scenicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.scenic_pos
     *
     * @return the value of scenic.scenic_pos
     *
     * @mbggenerated
     */
    public String getScenicPos() {
        return scenicPos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.scenic_pos
     *
     * @param scenicPos the value for scenic.scenic_pos
     *
     * @mbggenerated
     */
    public void setScenicPos(String scenicPos) {
        this.scenicPos = scenicPos == null ? null : scenicPos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.scenic_score
     *
     * @return the value of scenic.scenic_score
     *
     * @mbggenerated
     */
    public Integer getScenicScore() {
        return scenicScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.scenic_score
     *
     * @param scenicScore the value for scenic.scenic_score
     *
     * @mbggenerated
     */
    public void setScenicScore(Integer scenicScore) {
        this.scenicScore = scenicScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.scenic_ticket_price
     *
     * @return the value of scenic.scenic_ticket_price
     *
     * @mbggenerated
     */
    public Integer getScenicTicketPrice() {
        return scenicTicketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.scenic_ticket_price
     *
     * @param scenicTicketPrice the value for scenic.scenic_ticket_price
     *
     * @mbggenerated
     */
    public void setScenicTicketPrice(Integer scenicTicketPrice) {
        this.scenicTicketPrice = scenicTicketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.scenic_type
     *
     * @return the value of scenic.scenic_type
     *
     * @mbggenerated
     */
    public String getScenicType() {
        return scenicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.scenic_type
     *
     * @param scenicType the value for scenic.scenic_type
     *
     * @mbggenerated
     */
    public void setScenicType(String scenicType) {
        this.scenicType = scenicType == null ? null : scenicType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.province_id
     *
     * @return the value of scenic.province_id
     *
     * @mbggenerated
     */
    public Long getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.province_id
     *
     * @param provinceId the value for scenic.province_id
     *
     * @mbggenerated
     */
    public void setProvinceId(Long provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.city_id
     *
     * @return the value of scenic.city_id
     *
     * @mbggenerated
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.city_id
     *
     * @param cityId the value for scenic.city_id
     *
     * @mbggenerated
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    public String getScenicImg() {
		return scenicImg;
	}

	public void setScenicImg(String scenicImg) {
		this.scenicImg = scenicImg;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenic.del
     *
     * @return the value of scenic.del
     *
     * @mbggenerated
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenic.del
     *
     * @param del the value for scenic.del
     *
     * @mbggenerated
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    
	public Integer getTicketRemainder() {
		return ticketRemainder;
	}

	public void setTicketRemainder(Integer ticketRemainder) {
		this.ticketRemainder = ticketRemainder;
	}

	public Province getProvince() {
		return province;
	}

	public void setProvince(Province province) {
		this.province = province;
	}

	public City getCity() {
		return city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public List<Comment> getCommentList() {
		return commentList;
	}

	public void setCommentList(List<Comment> commentList) {
		this.commentList = commentList;
	}

	public List<Comment> getCommentListByUser() {
		return commentListByUser;
	}

	public void setCommentListByUser(List<Comment> commentListByUser) {
		this.commentListByUser = commentListByUser;
	}

	public List<Buyticket> getTicketListByUser() {
		return ticketListByUser;
	}

	public void setTicketListByUser(List<Buyticket> ticketListByUser) {
		this.ticketListByUser = ticketListByUser;
	}
}