package com.entity;

import java.util.Date;

public class Collect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.scenic_id
     *
     * @mbggenerated
     */
    private Long scenicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.datetime
     *
     * @mbggenerated
     */
    private Date datetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.del
     *
     * @mbggenerated
     */
    private Integer del;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.user_id
     *
     * @return the value of collect.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.user_id
     *
     * @param userId the value for collect.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.scenic_id
     *
     * @return the value of collect.scenic_id
     *
     * @mbggenerated
     */
    public Long getScenicId() {
        return scenicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.scenic_id
     *
     * @param scenicId the value for collect.scenic_id
     *
     * @mbggenerated
     */
    public void setScenicId(Long scenicId) {
        this.scenicId = scenicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.datetime
     *
     * @return the value of collect.datetime
     *
     * @mbggenerated
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.datetime
     *
     * @param datetime the value for collect.datetime
     *
     * @mbggenerated
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.del
     *
     * @return the value of collect.del
     *
     * @mbggenerated
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.del
     *
     * @param del the value for collect.del
     *
     * @mbggenerated
     */
    public void setDel(Integer del) {
        this.del = del;
    }
}